### ISSUE TITLE
Please add -s '94' to tcpdump

### ISSUE THREAD

**Issue by mestia** [DrGkill/Bandwidth-statistics#1]
very handy script,  but it will lost packets (packets dropped by kernel) on busy interfaces and/or for some kind of traffic because it captures complete packets.

By adding `--snapshot--length` parameter set to at least `94` for ipv4 traffic ( `14` seem to be fine too) the captured packet size is decreased and bandwidth counting is much more precise.

>  -s snaplen
>        --snapshot-length=snaplen
>               Snarf snaplen bytes of data from each  packet  rather  than  the
>               default of 262144 bytes.  Packets truncated because of a limited
>               snapshot are indicated in the output  with  ``[|proto]'',  where
>               proto  is the name of the protocol level at which the truncation
>               has occurred.  Note that taking larger snapshots both  increases
>               the amount of time it takes to process packets and, effectively,
>               decreases the amount of packet buffering.  This may cause  pack‐
>               ets to be lost.  You should limit snaplen to the smallest number
>               that will capture the protocol information you're interested in.
>               Setting snaplen to 0 sets it to the default of 262144, for back‐
>               wards compatibility with recent older versions of tcpdump.

I noticed the issue as I was getting only max 20MBps on a 1GB interface while other tools ( atop -n) would show that the interface is almost completely saturated. After setting -s do 94 I started to get >100MBps instead of 20MBps.

**Comment by DrGkill** [comment]
Ok! I'll have a look on this asap.

**Comment by DrGkill** [comment]
Done.
